library(MASS)
library(DAAG)
library(glmnet)
library(FrF2)
#Question 11.1
#Using the crime data set uscrime.txt from Questions 8.2, 9.1, and 10.1, build a regression model
#using:
#1. Stepwise regression
#2. Lasso
#3. Elastic net

#1. Stepwise regression
crime<- read.table("http://www.statsci.org/data/general/uscrime.txt",header=TRUE)
head(crime)

#Scale the predictors except the categorical(So)

crimes <- as.data.frame(scale(crime[,c(1,3,4,5,6,7,8,9,10,11,12,13,14,15)]))
crimes <- cbind(crime[,2],crimes,crime[,16]) # Add So Crime back in
colnames(crimes)[1] <- "So"
colnames(crimes)[16] <- "Crime"
head(crimes)

#Fit the model with all the predictors
lm <- lm(Crime ~ ., data = crime)
summary(lm)

#Use stepwise method to re-fit the model with all the predictors
stp<-stepAIC(lm, direction="both")
stp$anova
summary(stp)

#Cross validate the model.Since we only have 47 data points, we will use 47-fold cross-validation (leave-one-out cross-validation).
sst <- sum((crime$Crime - mean(crime$Crime))^2)
sse <- 0
for(i in 1:nrow(crimes)) {
        step_i = lm(Crime ~ M + Ed + Po1 + M.F + U1 + U2 + Ineq + Prob, data = crimes[-i,])
        pred_i <- predict(step_i,newdata=crimes[i,])
        sse <- sse + ((pred_i - crime[i,16])^2)
}
R2 <- 1 - sse/sst
R2

#For the scaled data, the fitted model is Crime=-6426.1+93.3*M+180.1*Ed+102.7*Po1+22.3*M.F-6086.6*U1+187.3*U2+61.3*Ineq-3796.0*Prob
#The adjusted R square is 0.744. After cross validation, it's 0.668        
        
#2. Lasso
set.seed(1234)
x<-as.matrix(crimes[,-16])
y<-as.matrix(crimes$Crime)
lasso<-cv.glmnet(x=x,y=y,alpha=1,
                nfolds = 5,type.measure="mse",family="gaussian")

#Output the coefficients of the variables selected by lasso

coef(lasso, s=lasso$lambda.min)

#Fitting a new model with these 11 variables

lasso2<-lm(Crime ~So+M+Ed+Po1+LF+M.F+NW+U1+U2+Ineq+Prob, data = crimes)
summary(lasso2)        
        
#The adjusted R square is 0.725, a little bit lower than the previous model. But hard to tell which one is better.

#Same as the previous one, cross validate the model using 47-fold cross-validation.
sse2 <- 0
for(i in 1:nrow(crimes)) {
        step_i <- lm(Crime ~ So+M+Ed+Po1+LF+M.F+NW+U1+U2+Ineq+Prob, data = crimes[-i,])
        pred_i <- predict(step_i,newdata=crimes[i,])
        sse2 <- sse2 + ((pred_i - crime[i,16])^2)
}
R2.2 <- 1 - sse2/sst
R2.2
#The cross validated R square is 0.596, much lower than the previous model (0.668),I would prefer the first model, which also have fewer predictors.

#3. Elastic net
#Use alpha from 0 to 1, by 0.1, and calculate the R-Squared values
set.seed(123)
R2.3<-c()
for (i in 0:10) {
        elastic<-cv.glmnet(x=x,y=y,alpha=i/10,nfolds = 5,type.measure="mse",family="gaussian")

        R2.3<-cbind(R2.3,elastic$glmnet.fit$dev.ratio[which(elastic$glmnet.fit$lambda == elastic$lambda.min)])
        
}

R2.3

#Best value of alpha
alpha_best <-(which.max(R2.3)-1)/10
alpha_best

#Re-fit the model using this alpha value.
set.seed(123)
elastic2<-cv.glmnet(x=x,y=y,alpha=alpha_best,nfolds = 5,type.measure="mse",family="gaussian")
coef(elastic2, s=elastic2$lambda.min)

#Fitting a new model with these 14 variables

elastic3<-lm(Crime ~So+M+Ed+Po1+LF+M.F+NW+U1+U2+Ineq+Prob, data = crimes)
summary(elastic3)        

#The adjusted R square is 0.725, same to the Lasso model. 
#Now do a cross validation on the model using 47-fold cross-validation.
sse2.3 <- 0
for(i in 1:nrow(crimes)) {
        step_i <- lm(Crime ~ So+M+Ed+Po1+Po2+LF+M.F+Pop+NW+U1+U2+Wealth+Ineq+Prob, data = crimes[-i,])
        pred_i <- predict(step_i,newdata=crimes[i,])
        sse2.3 <- sse2.3 + ((pred_i - crime[i,16])^2)
}
R2.3b <- 1 - sse2.3/sst
R2.3b
#The cross validated R square is 0.536. This is the lowest R square among the 3 models.In conclusion, the first model generated by stepwise method is the best.


#Question 12.1
#Describe a situation or problem from your job, everyday life, current events, etc., for which a design of
#experiments approach would be appropriate.

#The buble milk tea house would like to attract more people to buy their new arrival milk tea.They need to decide what cup design works best: 
#including the combination of font, size,picture of the milk / tea / buble / other ingrediants.

#Question 12.2
#To determine the value of 10 different yes/no features to the market value of a house (large yard, solar
#roof, etc.), a real estate agent plans to survey 50 potential buyers, showing a fictitious house with
#different combinations of features. To reduce the survey size, the agent wants to show just 16 fictitious houses. 

#Generate a 16 run, 10 factors, 2 level(yes/no) fractional factorial design
set.seed(123)
design<-FrF2(nruns = 16,nfactors = 10)
design

#Question 13.1
#For each of the following distributions, give an example of data that you would expect to follow this
#distribution (besides the examples already discussed in class).
#a. Binomial
#
#b. Geometric
#c. Poisson
#d. Exponential
#e. Weibull



        